import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';

const skill = readFileSync(new URL('../skills/smart-planner-cli/SKILL.md', import.meta.url), 'utf8');
assert.match(skill, /^---\nname: smart-planner-cli\n/);
assert.match(skill, /No completed Smart Planner run/);
assert.match(skill, /one final business-language confirmation/);
assert.match(skill, /references\/commands\.md/);
const canonical = readFileSync(new URL('../skills/optivise-cli/SKILL.md', import.meta.url), 'utf8');
assert.match(canonical, /^---\nname: optivise-cli\n/);
assert.match(canonical, /No completed Smart Planner run, no result/);
assert.match(canonical, /Remote-only hard boundary/);
assert.match(canonical, /Never install, import, download, or run a local optimization runtime/);
assert.match(canonical, /never run `pip`, `pip3`, `uv`, `conda`, `brew`, `apt`/);
assert.match(canonical, /The word “优化工具” in this skill means the supplied `optivise` CLI only/);
assert.match(canonical, /First-turn activation gate/);
assert.match(canonical, /setup --target workpartner/);
assert.match(canonical, /ready: true/);
assert.match(canonical, /PATH is resolving a stale binary/);
assert.match(canonical, /Never work around a stale binary by switching to the `codex` target/);
assert.match(canonical, /Merely reading the attached `SKILL\.md`/);
assert.match(canonical, /Customer-facing gate/);
assert.match(canonical, /Never make a preview table that resembles a recommendation/);
assert.match(canonical, /排班、派工、任务分配/);
assert.match(canonical, /explicitly reread the installed `optivise-cli\/SKILL\.md`/);
assert.match(canonical, /确认摘要只能复述数据范围/);
assert.match(canonical, /The confirmation is not a result preview/);
assert.match(canonical, /Customer reply check/);
assert.match(canonical, /feasibility rules and objective priorities/);
assert.match(canonical, /Do not ask them for a backend URL/);
assert.match(canonical, /one short readiness message/);
assert.match(canonical, /must contain only a short readiness message/);
assert.match(canonical, /Do not create command wrappers, edit `.zshrc`, `.bashrc`/);
assert.match(canonical, /Name each uploaded file in the confirmation/);
assert.match(canonical, /do not scaffold, remap, or rebuild it/);
assert.match(canonical, /solver names, solver runtime, bounds, or gap/);
assert.match(canonical, /do not print `OPTIMAL`/);
assert.match(canonical, /numeric objective weights/);
assert.match(canonical, /Translate them into business outcomes/);
assert.match(canonical, /downloadable file or attachment/);
assert.match(canonical, /Visible execution versus customer replies/);
assert.match(canonical, /There is no `local` mode/);
assert.match(canonical, /manifest\.solve\.json/);
assert.match(canonical, /Keep agent-authored progress notes short/);
assert.match(canonical, /Never reconstruct, hand-write, or complete a CSV from previews/);
assert.match(canonical, /optivise prepare --project/);
assert.match(canonical, /do not add `--profile`, `--project`, or `--mode` to `run`/);
assert.match(canonical, /max_time_in_seconds=1/);
assert.match(canonical, /Never report an unqualified utilization percentage/);
assert.match(canonical, /`resource_summary\.busy_minutes` is processing time only/);
assert.match(canonical, /Never describe `busy_minutes` as “含换线”/);
assert.match(canonical, /result or artifacts/);
const agent = readFileSync(new URL('../skills/smart-planner-cli/agents/openai.yaml', import.meta.url), 'utf8');
assert.match(agent, /display_name: "Optivise CLI"/);
assert.match(agent, /\$optivise-cli/);
assert.match(agent, /allow_implicit_invocation: true/);
const canonicalAgent = readFileSync(new URL('../skills/optivise-cli/agents/openai.yaml', import.meta.url), 'utf8');
assert.match(canonicalAgent, /allow_implicit_invocation: true/);
console.log('Skill metadata, provenance boundary, and customer journey passed');
